a = input('Digite alguma coisa:')
print('O tipo primitivo dessa variável é:', type(a))
print('Só tem espaços?', a.isspace())
print('É um número?', a.isnumeric())
print('É alfabético?', a.isalpha)
print('É alfanumérico?', a.isalnum)
